#!/bin/sh

echo "Running static analysis..."

git stash -q --keep-index
echo "Running git pre-push hook"

# Format code using KtLint, then run KtLint static analysis
./gradlew app:ktlintCheck --daemon

status=$?

git stash pop -q

if [ "$status" = 0 ] ; then
    echo "Static analysis found no problems."
    exit 0
else
    echo 1>&2 "Static analysis found violations it could not fix."
    exit 1
fi